name: Validate generated files
inputs:
  continue-on-error:
    description: "Continue on error"
    default: false
runs:
  using: 'composite'
  steps:
    - name: Don't validate quarantine files
      shell: bash
      run: |
        mkdir ${{ runner.temp }}/quarantine &&\
        mv `cat ./quarantine` ${{ runner.temp }}/quarantine &&
    - shell: bash
      run: wget https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar
    - name: Run validator
      shell: bash
      continue-on-error: {{ inputs.continue-on-error }}
      run: |
        java -jar validator_cli.jar generated/*.json \
             -version 4.0.1 -tx https://tx.dev.hl7.org.au/fhir \
             -ig hl7.fhir.au.core#1.0.0  -sct au \
             -level errors -jurisdiction au \
             -html-output g_validation.html -output g_validation.xml
    - name: Restore skipped files
      shell: bash
      run: mv ${{ runner.temp }}/quarantine ./generated

