name: Convert

on:
  workflow_dispatch:
    inputs:
      xlsFile:
        description: 'XLS file with test data'
        required: true

jobs:
  LoadNewCSV:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: |
        cd /tmp &&\
        wget https://github.com/hl7au/au-fhir-test-data-utils/releases/latest/download/xls-converter.zip &&\
        unzip xls-converter.zip &&\
        pip install xls_converter* &&\
        rm -rf xls_converter* xls-converter.zip
    - run: python -m xls_converter.main ${{ github.event.inputs.logLevel }} testdata-csv
    - uses: GrantBirki/git-diff-action@v2.6.1
      id: git-diff-action
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          delete-branch: true
          commit-message: Update test data
          title: Update test data
          body: New updates from ${{ github.event.inputs.logLevel }} 
          labels: automated-pr
          base: master
